### API
@hostname = http://127.0.0.1:3000/api
@token = Bearer 

################# ✅ Auth
### ✅ Login
POST {{hostname}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin@admin.com",
    "password": "password"
}

### ✅ Logout
POST {{hostname}}/logout
# Authorization: {{token}}

################# ✅ Category
### ✅ Get category
GET {{hostname}}/category
# Authorization: {{token}}

### ✅ Post category
POST {{hostname}}/category
Content-Type: application/json
Accept: application/json
# Authorization: {{token}}

{
    "name": "Test",
    "desc": "Test",
    "img": "Test"
}

### ✅ Show category
GET {{hostname}}/category/3
# Authorization: {{token}}

### ✅ Update category
PUT {{hostname}}/category/3
Content-Type: application/json
Accept: application/json
# Authorization: {{token}}

{
    "name": "Test",
    "desc": "Test",
    "img": "Test"
}

### ✅ Delete category
DELETE {{hostname}}/category/3/delete
# Authorization: {{token}}

################# ✅ Product
### ✅ Get product
GET {{hostname}}/product
# Authorization: {{token}}

### ✅ Post product
POST {{hostname}}/product
Content-Type: application/json
Accept: application/json
# Authorization: {{token}}

{
    "name": "Test",
    "desc": "Test",
    "img": "Test",
    "price": 10,
    "categoryId": 1
}

### ✅ Show product
GET {{hostname}}/product/3
# Authorization: {{token}}

### ✅ Update product
PUT {{hostname}}/product/3
Content-Type: application/json
Accept: application/json
# Authorization: {{token}}

{
    "name": "Test",
    "desc": "Test",
    "img": "Test",
    "price": 20,
    "categoryId": 1
}

### ✅ Delete product
DELETE {{hostname}}/product/3/delete
# Authorization: {{token}}

################# ✅ User
### ✅ Get user
GET {{hostname}}/user
# Authorization: {{token}}

### ✅ Post user
POST {{hostname}}/user
Content-Type: application/json
Accept: application/json
# Authorization: {{token}}

{
    "name": "Test",
    "email": "Test",
    "age": 20,
}

### ✅ Show user
GET {{hostname}}/user/3
# Authorization: {{token}}

### ✅ Update user
PUT {{hostname}}/user/3
Content-Type: application/json
Accept: application/json
# Authorization: {{token}}

{
    "name": "Test",
    "email": "test",
    "age": 20
}

### ✅ Delete user
DELETE {{hostname}}/user/3/delete
# Authorization: {{token}}
